In [40]:
import pandas as pd
import numpy as np

base = pd.read_csv('credit_data.csv')
base.loc[base.age < 0, 'age'] = 40.92
               
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(previsores[:, 1:4])
previsores[:, 1:4] = imputer.transform(previsores[:, 1:4])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25, random_state=0)


In [41]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
import collections

for Kernel in ['linear', 'poly', 'rbf', 'sigmoid']:
    print('\ninicio da analise Kenerl {}'.format(Kernel))
    classificador  = SVC(kernel= Kernel, random_state = 1, C = 2.0, gamma='auto')
    classificador .fit(previsores_treinamento, classe_treinamento)
    previsoes  = classificador .predict(previsores_teste)
    previsoes  = classificador .predict(previsores_teste)
    precisao  = accuracy_score(classe_teste, previsoes )
    matrix  = confusion_matrix(classe_teste, previsoes )
    print('precisao', Kernel, precisao )
    print('precisao', Kernel, '\n', matrix)


inicio da analise Kenerl linear
precisao linear 0.946
precisao linear 
 [[422  14]
 [ 13  51]]

inicio da analise Kenerl poly
precisao poly 0.968
precisao poly 
 [[431   5]
 [ 11  53]]

inicio da analise Kenerl rbf
precisao rbf 0.988
precisao rbf 
 [[434   2]
 [  4  60]]

inicio da analise Kenerl sigmoid
precisao sigmoid 0.826
precisao sigmoid 
 [[387  49]
 [ 38  26]]


In [42]:
collections.Counter(classe_teste)

Counter({1: 64, 0: 436})